cask_args appdir: "~/Applications", require_sha: true

# Tools
brew "stow"
brew "bat"
brew "go"
brew "tree"
brew "ffmpeg"
brew "bat"
brew "neovim"
brew "pipx"
brew "ripgrep"
brew "fzf"
brew "tree-sitter"
brew "deno"
brew "lazygit"
brew "difftastic"
brew "sqlite"
brew "starship"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"
brew "zsh-vi-mode"

# Apps
cask "obsidian"
cask "ollama"
cask "appcleaner"
cask "flux"
cask "ghostty"
cask "ngrok"
cask "postman"
cask "spotify"
cask "discord"
cask "orbstack"
cask "raycast"

# Browsers
cask "orion"
cask "google-chrome"
cask "firefox"
