#!/bin/bash

# Install Homebrew if not installed
if ! command -v brew &> /dev/null; then
    echo "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
else
    echo "Homebrew already installed."
fi

echo "Installing packages from Brewfile..."
brew bundle

echo "Creating symlinks..."
stow -v -t ~ home
ln -s /Volumes/Local/02.dev/ai ~/ai
ln -s /Volumes/Local/02.dev/sandbox ~/sandbox
ln -s /Volumes/Local/02.dev/.localrc ~/.localrc

echo "Installation complete!"
