#!/bin/bash

# Install Homebrew if not installed
if ! command -v brew &> /dev/null; then
    echo "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
else
    echo "Homebrew already installed."
fi

echo "Installing packages from Brewfile..."
brew bundle

echo "Creating symlinks from dotfiles"
stow -v -t ~ home

echo "Creating symlinks from local ssd"
cd /Volumes/Local/02.dev
stow -v -t ~ home --ignore='\.DS_Store' --ignore='\._.*' --ignore='\.AppleDouble'

echo "Installation complete!"
