gui:
  border: "single"
  theme:
    lightTheme: true
    activeBorderColor:
      - bold
os:
  edit: "nvim {{filename}}"
  editAtLine: "nvim --line={{line}} {{filename}}"
  editAtLineAndWait: "nvim --block --line={{line}} {{filename}}"
  editInTerminal: true
  openDirInEditor: "nvim {{dir}}"
  open: "nvim {{filename}}"
# git:
#   paging:
#     externalDiffCommand: difft --color=auto
